name: Codex Reminder

on:
  issues:
    types: [opened, labeled]

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Echo reminder
        run: echo "Review Codex tasks and prioritize."